// generated 2006/11/14 21:10:50 CET by tobias@THINKPAD-T43.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/tobias/Projekte/gninjam/gninjam.glade
// for gtk 2.10.6 and gtkmm 2.10.2
//
// Please modify the corresponding derived classes in ./src/gNinjamClient.hh and./src/gNinjamClient.cc

#ifndef _GNINJAMCLIENT_GLADE_HH
#  define _GNINJAMCLIENT_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/scale.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/entry.h>
#include <gtkmm/treeview.h>
#include <gtkmm/textview.h>
#include <gtkmm/label.h>
#include <gtkmm/progressbar.h>
#include <gtkmm/statusbar.h>

class gNinjamClient_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::HScale * hscale_metronome_volume;
        class Gtk::HScale * hscale_master_pan;
        class Gtk::HScale * hscale_metronome_pan;
        class Gtk::CheckButton * checkbutton_master_mute;
        class Gtk::CheckButton * checkbutton_metronome_mute;
        class Gtk::Entry * entry1;
        class Gtk::HScale * hscale_master_volume;
        class Gtk::TreeView * treeview1;
        class Gtk::TreeView * treeview2;
        class Gtk::TextView * textview1;
        class Gtk::Entry * chat_entry;
        class Gtk::Label * label_chat;
        class Gtk::ProgressBar * progressbar1;
        class Gtk::Statusbar * statusbar1;
        
        gNinjamClient_glade();
        
        ~gNinjamClient_glade();
private:
        virtual void on_verbinden1_activate() = 0;
        virtual void on_trennen1_activate() = 0;
        virtual void on_beenden1_activate() = 0;
        virtual void on_ausschneiden1_activate() = 0;
        virtual void on_kopieren1_activate() = 0;
        virtual void on_einf__gen1_activate() = 0;
        virtual void on_l__schen1_activate() = 0;
        virtual void on_info1_activate() = 0;
        virtual void on_hscale_metronome_volume_value_changed() = 0;
        virtual void on_hscale_master_pan_value_changed() = 0;
        virtual void on_hscale_metronome_pan_value_changed() = 0;
        virtual void on_checkbutton_master_mute_toggled() = 0;
        virtual void on_checkbutton_metronome_mute_toggled() = 0;
        virtual void on_hscale_master_volume_value_changed() = 0;
        virtual void on_button_send_clicked() = 0;
};
#endif
