// generated 2006/11/22 15:07:58 CET by tobias@THINKPAD-T43.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/tobias/src/svn/gninjam/trunk/gninjam.glade
// for gtk 2.10.6 and gtkmm 2.10.3
//
// Please modify the corresponding derived classes in ./src/RemoteUserFrame.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "RemoteUserFrame_glade.hh"
#include <gtkmm/alignment.h>

RemoteUserFrame_glade::RemoteUserFrame_glade(GlademmData *gmm_data
)
{  
   
   Gtk::Frame *RemoteUserFrame = this;
   vbox = Gtk::manage(new class Gtk::VBox(false, 0));
   
   Gtk::Alignment *alignment4 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   label = Gtk::manage(new class Gtk::Label(""));
   vbox->set_name("vbox");
   alignment4->set_name("alignment4");
   alignment4->add(*vbox);
   label->set_name("label");
   label->set_alignment(0.5,0.5);
   label->set_padding(0,0);
   label->set_justify(Gtk::JUSTIFY_LEFT);
   label->set_line_wrap(false);
   label->set_use_markup(true);
   label->set_selectable(false);
   RemoteUserFrame->set_name("RemoteUserFrame");
   RemoteUserFrame->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   RemoteUserFrame->set_label_align(0,0.5);
   RemoteUserFrame->add(*alignment4);
   RemoteUserFrame->set_label_widget(*label);
   vbox->show();
   alignment4->show();
   label->show();
   RemoteUserFrame->show();
}

RemoteUserFrame_glade::~RemoteUserFrame_glade()
{  
}
