// generated 2006/11/16 1:22:27 CET by tobias@THINKPAD-T43.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/tobias/src/svn/gninjam/trunk/gninjam.glade
// for gtk 2.10.6 and gtkmm 2.10.3
//
// Please modify the corresponding derived classes in ./src/vbox_remote.hh and./src/vbox_remote.cc

#ifndef _VBOX_REMOTE_GLADE_HH
#  define _VBOX_REMOTE_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/box.h>

class vbox_remote_glade : public Gtk::VBox
{  
protected:
        
        class Gtk::VBox * vbox_remote;
        
        vbox_remote_glade(GlademmData *gmm_data);
        
        ~vbox_remote_glade();
};
#endif
