// generated 2006/11/22 14:38:04 CET by tobias@THINKPAD-T43.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/tobias/src/svn/gninjam/trunk/gninjam.glade
// for gtk 2.10.6 and gtkmm 2.10.3
//
// Please modify the corresponding derived classes in ./src/vbox_remote_channel.hh and./src/vbox_remote_channel.cc

#ifndef _VBOX_REMOTE_CHANNEL_GLADE_HH
#  define _VBOX_REMOTE_CHANNEL_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/box.h>
#include <gtkmm/entry.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/combobox.h>
#include <gtkmm/progressbar.h>
#include <gtkmm/scale.h>

class vbox_remote_channel_glade : public Gtk::VBox
{  
protected:
        
        class Gtk::Entry * entry_remote_channelname;
        class Gtk::CheckButton * checkbutton_remote_receive;
        class Gtk::ComboBox * combobox_remote_output;
        class Gtk::ProgressBar * progressbar_remote;
        class Gtk::HScale * hscale_remote_volume;
        class Gtk::HScale * hscale_remote_pan;
        class Gtk::CheckButton * checkbutton_remote_mute;
        class Gtk::CheckButton * checkbutton_remote_solo;
        class Gtk::CheckButton * checkbutton_remote_stereo;
        
        vbox_remote_channel_glade(GlademmData *gmm_data);
        
        ~vbox_remote_channel_glade();
private:
        virtual void on_checkbutton_remote_receive_toggled() = 0;
        virtual void on_combobox_remote_output_changed() = 0;
        virtual void on_hscale_remote_volume_value_changed() = 0;
        virtual void on_hscale_remote_pan_value_changed() = 0;
        virtual void on_checkbutton_remote_mute_toggled() = 0;
        virtual void on_checkbutton_remote_solo_toggled() = 0;
        virtual void on_checkbutton_remote_stereo_toggled() = 0;
};
#endif
