// generated 2006/11/18 2:41:09 CET by tobias@THINKPAD-T43.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/tobias/src/svn/gninjam/trunk/gninjam.glade
// for gtk 2.10.6 and gtkmm 2.10.3
//
// Please modify the corresponding derived classes in ./src/window_preferences.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "window_preferences_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/label.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/adjustment.h>
#include <gtkmm/table.h>

window_preferences_glade::window_preferences_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  window_preferences = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::Label *label10 = Gtk::manage(new class Gtk::Label("Audio driver:"));
   combobox_audiodriver = Gtk::manage(new class Gtk::ComboBox());
   combobox_savelocalaudio = Gtk::manage(new class Gtk::ComboBox());
   
   Gtk::Label *label12 = Gtk::manage(new class Gtk::Label("Save local audio:"));
   Gtk::Label *label11 = Gtk::manage(new class Gtk::Label("Session directory:"));
   entry_sessiondir = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label13 = Gtk::manage(new class Gtk::Label("Audio config string:"));
   entry_audioconfigstring = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label14 = Gtk::manage(new class Gtk::Label("Ogg bitrate:"));
   checkbutton_savelog = Gtk::manage(new class Gtk::CheckButton("Save log files"));
   
   Gtk::Button *button_abort = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   Gtk::Button *button_apply = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-apply")));
   Gtk::Button *button_ok = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   Gtk::HButtonBox *hbuttonbox1 = Gtk::manage(new class Gtk::HButtonBox(Gtk::BUTTONBOX_END, 4));
   Gtk::Adjustment *spinbutton_oggbitrate_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 600, 1, 10, 10));
   spinbutton_oggbitrate = Gtk::manage(new class Gtk::SpinButton(*spinbutton_oggbitrate_adj, 1, 0));
   
   Gtk::Table *table3 = Gtk::manage(new class Gtk::Table(2, 2, false));
   label10->set_name("label10");
   label10->set_alignment(0,0.5);
   label10->set_padding(0,0);
   label10->set_justify(Gtk::JUSTIFY_LEFT);
   label10->set_line_wrap(false);
   label10->set_use_markup(false);
   label10->set_selectable(false);
   combobox_audiodriver->set_name("combobox_audiodriver");
   combobox_savelocalaudio->set_name("combobox_savelocalaudio");
   label12->set_name("label12");
   label12->set_alignment(0,0.5);
   label12->set_padding(0,0);
   label12->set_justify(Gtk::JUSTIFY_LEFT);
   label12->set_line_wrap(false);
   label12->set_use_markup(false);
   label12->set_selectable(false);
   label11->set_name("label11");
   label11->set_alignment(0,0.5);
   label11->set_padding(0,0);
   label11->set_justify(Gtk::JUSTIFY_LEFT);
   label11->set_line_wrap(false);
   label11->set_use_markup(false);
   label11->set_selectable(false);
   entry_sessiondir->set_name("entry_sessiondir");
   entry_sessiondir->set_flags(Gtk::CAN_FOCUS);
   entry_sessiondir->set_visibility(true);
   entry_sessiondir->set_editable(true);
   entry_sessiondir->set_max_length(0);
   entry_sessiondir->set_text("");
   entry_sessiondir->set_has_frame(true);
   entry_sessiondir->set_activates_default(false);
   label13->set_name("label13");
   label13->set_alignment(0,0.5);
   label13->set_padding(0,0);
   label13->set_justify(Gtk::JUSTIFY_LEFT);
   label13->set_line_wrap(false);
   label13->set_use_markup(false);
   label13->set_selectable(false);
   entry_audioconfigstring->set_name("entry_audioconfigstring");
   entry_audioconfigstring->set_flags(Gtk::CAN_FOCUS);
   entry_audioconfigstring->set_visibility(true);
   entry_audioconfigstring->set_editable(true);
   entry_audioconfigstring->set_max_length(0);
   entry_audioconfigstring->set_text("");
   entry_audioconfigstring->set_has_frame(true);
   entry_audioconfigstring->set_activates_default(false);
   label14->set_name("label14");
   label14->set_alignment(0,0.5);
   label14->set_padding(0,0);
   label14->set_justify(Gtk::JUSTIFY_LEFT);
   label14->set_line_wrap(false);
   label14->set_use_markup(false);
   label14->set_selectable(false);
   checkbutton_savelog->set_name("checkbutton_savelog");
   checkbutton_savelog->set_flags(Gtk::CAN_FOCUS);
   checkbutton_savelog->set_relief(Gtk::RELIEF_NORMAL);
   checkbutton_savelog->set_mode(true);
   checkbutton_savelog->set_active(false);
   button_abort->set_name("button_abort");
   button_abort->set_flags(Gtk::CAN_FOCUS);
   button_abort->set_flags(Gtk::CAN_DEFAULT);
   button_abort->set_relief(Gtk::RELIEF_NORMAL);
   button_apply->set_name("button_apply");
   button_apply->set_flags(Gtk::CAN_FOCUS);
   button_apply->set_flags(Gtk::CAN_DEFAULT);
   button_apply->set_relief(Gtk::RELIEF_NORMAL);
   button_ok->set_name("button_ok");
   button_ok->set_flags(Gtk::CAN_FOCUS);
   button_ok->set_flags(Gtk::CAN_DEFAULT);
   button_ok->set_relief(Gtk::RELIEF_NORMAL);
   hbuttonbox1->set_name("hbuttonbox1");
   hbuttonbox1->pack_start(*button_abort);
   hbuttonbox1->pack_start(*button_apply);
   hbuttonbox1->pack_start(*button_ok);
   spinbutton_oggbitrate->set_name("spinbutton_oggbitrate");
   spinbutton_oggbitrate->set_flags(Gtk::CAN_FOCUS);
   spinbutton_oggbitrate->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbutton_oggbitrate->set_numeric(true);
   spinbutton_oggbitrate->set_digits(0);
   spinbutton_oggbitrate->set_wrap(false);
   table3->set_name("table3");
   table3->set_border_width(4);
   table3->set_row_spacings(4);
   table3->set_col_spacings(4);
   table3->attach(*label10, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*combobox_audiodriver, 1, 2, 0, 1, Gtk::FILL, Gtk::FILL, 0, 0);
   table3->attach(*combobox_savelocalaudio, 1, 2, 3, 4, Gtk::FILL, Gtk::FILL, 0, 0);
   table3->attach(*label12, 0, 1, 3, 4, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*label11, 0, 1, 2, 3, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*entry_sessiondir, 1, 2, 2, 3, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*label13, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*entry_audioconfigstring, 1, 2, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*label14, 0, 1, 4, 5, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*checkbutton_savelog, 1, 2, 5, 6, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*hbuttonbox1, 0, 2, 6, 7, Gtk::EXPAND|Gtk::FILL, Gtk::FILL, 0, 0);
   table3->attach(*spinbutton_oggbitrate, 1, 2, 4, 5, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   window_preferences->set_name("window_preferences");
   window_preferences->set_title("Preferences");
   window_preferences->set_modal(false);
   window_preferences->property_window_position().set_value(Gtk::WIN_POS_NONE);
   window_preferences->set_resizable(true);
   window_preferences->property_destroy_with_parent().set_value(false);
   window_preferences->add(*table3);
   label10->show();
   combobox_audiodriver->show();
   combobox_savelocalaudio->show();
   label12->show();
   label11->show();
   entry_sessiondir->show();
   label13->show();
   entry_audioconfigstring->show();
   label14->show();
   checkbutton_savelog->show();
   button_abort->show();
   button_apply->show();
   button_ok->show();
   hbuttonbox1->show();
   spinbutton_oggbitrate->show();
   table3->show();
   button_abort->signal_clicked().connect(SigC::slot(*this, &window_preferences_glade::on_button_abort_clicked), false);
   button_apply->signal_clicked().connect(SigC::slot(*this, &window_preferences_glade::on_button_apply_clicked), false);
   button_ok->signal_clicked().connect(SigC::slot(*this, &window_preferences_glade::on_button_ok_clicked), false);
   window_preferences->signal_show().connect(SigC::slot(*this, &window_preferences_glade::on_window_preferences_show), false);
}

window_preferences_glade::~window_preferences_glade()
{  delete gmm_data;
}
