// generated 2008/2/4 20:42:24 CET by tobias@THINKPAD-T43.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/tobias/src/svn/gninjam/trunk/gninjam.glade
// for gtk 2.12.0 and gtkmm 2.12.0
//
// Please modify the corresponding derived classes in ./src/dialog_connect.hh and./src/dialog_connect.cc

#ifndef _DIALOG_CONNECT_GLADE_HH
#  define _DIALOG_CONNECT_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/entry.h>
#include <gtkmm/label.h>
#include <gtkmm/checkbutton.h>

class dialog_connect_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * dialog_connect;
        class Gtk::Entry * entry_hostname;
        class Gtk::Entry * entry_username;
protected:
        class Gtk::Label * label6;
public:
        class Gtk::Entry * entry_password;
        class Gtk::CheckButton * checkbutton_anonymous;
protected:
        
        dialog_connect_glade();
        
        ~dialog_connect_glade();
private:
        virtual void on_checkbutton_anonymous_toggled() = 0;
};
#endif
