Document: gninjam
Title: Debian gninjam Manual
Author: <insert document author here>
Abstract: This manual describes what gninjam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gninjam/gninjam.sgml.gz

Format: postscript
Files: /usr/share/doc/gninjam/gninjam.ps.gz

Format: text
Files: /usr/share/doc/gninjam/gninjam.text.gz

Format: HTML
Index: /usr/share/doc/gninjam/html/index.html
Files: /usr/share/doc/gninjam/html/*.html

  
