// generated 2006/11/22 14:40:18 CET by tobias@THINKPAD-T43.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/tobias/src/svn/gninjam/trunk/gninjam.glade
// for gtk 2.10.6 and gtkmm 2.10.3
//
// Please modify the corresponding derived classes in ./src/gNinjamClient.hh and./src/gNinjamClient.cc

#ifndef _GNINJAMCLIENT_GLADE_HH
#  define _GNINJAMCLIENT_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/scale.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/progressbar.h>
#include <gtkmm/combobox.h>
#include <gtkmm/handlebox.h>
#include "vbox_local.hh"
#include <gtkmm/frame.h>
#include "vbox_remote.hh"
#include <gtkmm/textview.h>
#include <gtkmm/entry.h>
#include <gtkmm/label.h>

class gNinjamClient_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::HScale * hscale_metronome_volume;
        class Gtk::HScale * hscale_master_pan;
        class Gtk::HScale * hscale_metronome_pan;
        class Gtk::CheckButton * checkbutton_master_mute;
        class Gtk::CheckButton * checkbutton_metronome_mute;
        class Gtk::HScale * hscale_master_volume;
        class Gtk::ProgressBar * progressbar_master;
        class Gtk::CheckButton * checkbutton_metronome_stereo;
        class Gtk::ComboBox * combobox_metronome_output;
        class Gtk::HandleBox * handlebox1;
        class vbox_local * vbox_local;
        class Gtk::Frame * frame_local;
        class vbox_remote * vbox_remote;
        class Gtk::Frame * frame_remote;
        class Gtk::TextView * textview1;
        class Gtk::Entry * chat_entry;
        class Gtk::Label * label_chat;
        class Gtk::Frame * frame_chat;
        class Gtk::ProgressBar * progressbar1;
        class Gtk::Label * label_connection_status;
        class Gtk::Label * label_audio_info;
        
        gNinjamClient_glade();
        
        ~gNinjamClient_glade();
private:
        virtual void on_neu1_activate() = 0;
        virtual void on_verbinden1_activate() = 0;
        virtual void on_trennen1_activate() = 0;
        virtual void on_beenden1_activate() = 0;
        virtual void on_ausschneiden1_activate() = 0;
        virtual void on_kopieren1_activate() = 0;
        virtual void on_einf__gen1_activate() = 0;
        virtual void on_l__schen1_activate() = 0;
        virtual void on_einstellungen1_activate() = 0;
        virtual void on_local_channels1_activate() = 0;
        virtual void on_remote_channels1_activate() = 0;
        virtual void on_chat1_activate() = 0;
        virtual void on_info1_activate() = 0;
        virtual void on_hscale_metronome_volume_value_changed() = 0;
        virtual void on_hscale_master_pan_value_changed() = 0;
        virtual void on_hscale_metronome_pan_value_changed() = 0;
        virtual void on_checkbutton_master_mute_toggled() = 0;
        virtual void on_checkbutton_metronome_mute_toggled() = 0;
        virtual void on_hscale_master_volume_value_changed() = 0;
        virtual void on_checkbutton_metronome_stereo_toggled() = 0;
        virtual void on_combobox_metronome_output_changed() = 0;
        virtual void on_chat_entry_activate() = 0;
};
#endif
