// generated 2006/11/15 18:53:44 CET by tobias@THINKPAD-T43.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/tobias/src/svn/gninjam/trunk/gninjam.glade
// for gtk 2.10.6 and gtkmm 2.10.3
//
// Please modify the corresponding derived classes in ./src/window_preferences.hh and./src/window_preferences.cc

#ifndef _WINDOW_PREFERENCES_GLADE_HH
#  define _WINDOW_PREFERENCES_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/combobox.h>
#include <gtkmm/label.h>

class window_preferences_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * window_preferences;
protected:
        class Gtk::ComboBox * combobox1;
        class Gtk::Label * filechooserbutton1;
        
        window_preferences_glade();
        
        ~window_preferences_glade();
private:
        virtual void on_button_abort_clicked() = 0;
        virtual void on_button_apply_clicked() = 0;
        virtual void on_button_ok_clicked() = 0;
};
#endif
